server:
  port: 8090
spring:
  application:
    name: Electromagnetic-app
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/regie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  servlet:
    multipart:
      max-request-size: 100MB #改为自己的想要的
      max-file-size: 100MB #改为自己的想要的
      enabled: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  type-aliases-package: com.scj.reggie_take_out.entity
fileSystem:
#  device-path: D:\VUE\test\reggie_take_out\src\main\resources\backend\images\device_model\
#  building-path: D:\VUE\test\reggie_take_out\src\main\resources\backend\images\building_model\
  device-path: E:\电磁态势呈现\例会文件\reggie_take_out\src\main\resources\backend\images\device_model\
  building-path: E:\电磁态势呈现\例会文件\reggie_take_out\src\main\resources\backend\images\building_model\